### PR TITLE
feat: unlimited max available

### LINKED ISSUE #115: Dont limit amount of product to add
It is required that there is no limit to the number of products to be added to the cart.

All available quantity checking logic must be removed.

All available quantity checking logic must be removed.
chrome_KkeZdvS5EH

### PR DESCRIPTION
**Pull request by AdrianFagilde**
##Description:

Delete max-available, and online infinity amount products available 

fixes #115

### CODE REVIEW

**Review by Eghinner — APPROVED** [review]

**Review by e-azocar — APPROVED** [review]

**Comment by heliomar-pena** [comment]
Deploy preview:
https://deploy-preview-117--did-app.netlify.app/

@angelik0828 please check

CCO: @e-azocar @Eghinner

**Review by heliomar-pena — APPROVED** [review]
Works fine to me! good job @AdrianFagilde 
image

**Comment by heliomar-pena** [comment]
@AdrianFagilde @Eghinner please add a How to test for ease QA testing

**Comment by Eghinner** [comment]
> @AdrianFagilde @Eghinner please add a How to test for ease QA testing

@angelik0828 Steps to test

1. Login
2. Go to providers
3. Select 'tribeca'
4. Buy something
5. Go to the cart
6. Edit the amount of product

**Comment by angelik0828** [comment]
## ✔️ Validation is done

- When adding a product and placing a quantity, it does not show any limit or stock message.
- By having several products in the list, it allows me to add each of them without any problem.
 
image
image

**Review by angelik0828 — APPROVED** [review]

**Pull request merged**
